// <auto-generated />
using GitHubPortal.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GitHubDatabase_Fessler.Migrations
{
    [DbContext(typeof(PortalDbContext))]
    [Migration("20260313004551_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GitHubPortal.Models.PortalLink", b =>
                {
                    b.Property<int>("PortalLinkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PortalLinkId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PortalLinkId");

                    b.ToTable("PortalLinks");

                    b.HasData(
                        new
                        {
                            PortalLinkId = 1,
                            Description = "This is what you're using right now! GitHub Portal is a data-driven web application built with ASP.NET Core MVC that allows users to manage a curated list of useful links.",
                            Name = "GitHub Database",
                            Url = "https://github.com/fesslerjo2024/GitHubDatabase_Fessler"
                        },
                        new
                        {
                            PortalLinkId = 2,
                            Description = "My personal portfolio website showcasing my projects, skills, resume, and contact information. Built with HTML, CSS, and JavaScript, the site is fully responsive and optimized for a smooth user experience.",
                            Name = "AWS Cloud Portfolio Website",
                            Url = "https://github.com/fesslerjo2024/AWSCloudPortfolioWebsite_Fessler"
                        },
                        new
                        {
                            PortalLinkId = 3,
                            Description = "MarketMates is a relational database system designed as a final project for Database Concepts, Design, and Application.",
                            Name = "MarketMates Database",
                            Url = "https://github.com/fesslerjo2024/MarketMates_Database"
                        },
                        new
                        {
                            PortalLinkId = 4,
                            Description = "Final Project for Java Class using Open-Meteo and Zippopotam.us APIs.",
                            Name = "Weather App Java",
                            Url = "https://github.com/fesslerjo2024/WeatherAppJava_Fessler"
                        },
                        new
                        {
                            PortalLinkId = 5,
                            Description = "This project was made in my Java class to demonstrate how to use an array as well as make objects.",
                            Name = "Game Interface",
                            Url = "https://github.com/fesslerjo2024/GameInterface_Fessler"
                        },
                        new
                        {
                            PortalLinkId = 6,
                            Description = "Assignment for my Java class to teach us how to use JavaFX to create random circles and color them when they overlap.",
                            Name = "JavaFX Circle Overlap",
                            Url = "https://github.com/fesslerjo2024/JavaFXCircleOverlap"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
