// <auto-generated />
using GitHubPortal.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GitHubDatabase_Fessler.Migrations
{
    [DbContext(typeof(PortalDbContext))]
    partial class PortalDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GitHubPortal.Models.PortalLink", b =>
                {
                    b.Property<int>("PortalLinkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PortalLinkId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PortalLinkId");

                    b.ToTable("PortalLinks");

                    b.HasData(
                        new
                        {
                            PortalLinkId = 1,
                            Description = "The world's leading platform for version control and collaborative software development.",
                            Name = "GitHub",
                            Url = "https://github.com"
                        },
                        new
                        {
                            PortalLinkId = 2,
                            Description = "The largest Q&A community for developers to learn, share knowledge, and build careers.",
                            Name = "Stack Overflow",
                            Url = "https://stackoverflow.com"
                        },
                        new
                        {
                            PortalLinkId = 3,
                            Description = "Official Microsoft documentation for .NET, ASP.NET Core, Azure, and all Microsoft technologies.",
                            Name = "Microsoft Docs",
                            Url = "https://docs.microsoft.com"
                        },
                        new
                        {
                            PortalLinkId = 4,
                            Description = "Mozilla's comprehensive reference for HTML, CSS, and JavaScript web development.",
                            Name = "MDN Web Docs",
                            Url = "https://developer.mozilla.org"
                        },
                        new
                        {
                            PortalLinkId = 5,
                            Description = "The package manager for .NET — browse and download open-source libraries for your projects.",
                            Name = "NuGet Gallery",
                            Url = "https://www.nuget.org"
                        },
                        new
                        {
                            PortalLinkId = 6,
                            Description = "Official Bootstrap 5 documentation for building responsive, mobile-first websites.",
                            Name = "Bootstrap Docs",
                            Url = "https://getbootstrap.com/docs"
                        },
                        new
                        {
                            PortalLinkId = 7,
                            Description = "Microsoft's official EF Core documentation for database access in .NET applications.",
                            Name = "Entity Framework Docs",
                            Url = "https://learn.microsoft.com/en-us/ef/core/"
                        },
                        new
                        {
                            PortalLinkId = 8,
                            Description = "Beginner-friendly tutorials and references for HTML, CSS, JavaScript, SQL, and more.",
                            Name = "W3Schools",
                            Url = "https://www.w3schools.com"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
